#****************************************************************************
# Copyright (c) 2015, This software is the property of IntelligentDots and
# shall not be reproduced, copied, or distributed without written
# permission. Joshua
#
# --- ArrivalTime ---
#****************************************************************************

NOTSHARED := IdApp

include ../Amos.mk

#****************************************************************************

all: $(FILE_EXE)

#****************************************************************************
# *** end of Makefile ***
